name: Test App Execution

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit app in background
      env:
        OPENAI_API_BASE: dummy_base
        OPENAI_API_KEY: dummy_key
        OPENAI_API_VERSION: dummy_version
        OPENAI_API_DEPLOY_VISION: dummy_deployment
      run: streamlit run GPT4V_Streamlit.py --server.headless true --server.port 8501 &

    - name: Wait for app to start
      run: sleep 15

    - name: Test if app is accessible
      run: curl -f http://localhost:8501 || (echo "App failed to start" && exit 1)

    - name: Kill app process
      run: pkill -f streamlit || true